// <auto-generated />
namespace AcademiaoUltimo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class novaMigração : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(novaMigração));
        
        string IMigrationMetadata.Id
        {
            get { return "202411030447531_novaMigração"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
